### ISSUE TITLE
[Chore] constants, interfaces 폴더 추가

### ISSUE THREAD

**Issue by hyeyoon100** [INSOPT-CDS-Behance/server#12]
## Issue

constants 퐆더: `index.ts`, `response.ts`, `responseMessage.ts`, `statusCode.ts`
interfacfes 폴더: 각 API에 필요한 DTO 생성

## To-do

- [ ] constants 폴더 생성
- [ ] interaces 폴더 생성
- [ ] constants 내 파일들 추가
- [ ] interfaces 폴더 내 API별 폴더 생성
